formificApp/formificApp/__init__.py
from flask import Flask
from database import init_db
import error_handlers
from auth.controller import auth
from views.controller import views


# Initialize database
init_db()

# Define the application object
app = Flask(__name__)

# Register blueprints
app.register_blueprint(error_handlers.blueprint)
app.register_blueprint(auth)
app.register_blueprint(views)

# Run server.
if __name__ == '__main__':
    app.secret_key = 'super_secret_key'
    app.debug = True
    app.run()

formificApp/formificApp/views/controller.py
from flask import (
    Flask, render_template, request, redirect, url_for,
    flash, jsonify, abort, Blueprint
    )
from sqlalchemy import asc
from database import init_db
from database import session
from formific_models import User, Medium, ArtItem
from flask import session as login_session
from flask import make_response
from functools import wraps


views = Blueprint('views', __name__, template_folder='/var/www/formificApp/formificApp/templates/')


def login_required(func):
    """ Check if user is logged in.

    This is a decorator that verfies whether a user is logged in before
    allowing access to the requested resource. If they are
    not logged in, they are redirected to the login page.
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        if 'username' not in login_session:
            return redirect('/login')
        else:
            return func(*args, **kwargs)
    return wrapper


def item_modification_authentication(func):
    """ Check if user is owner of an item.

    This is a decorator that checks whether a user is the owner 
    of a specific item before they are allowed to edit or delete it.
    If they are not the owner, they are flashed a message.
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        item_id = kwargs['item_id']
        item = session.query(ArtItem).filter_by(id=item_id).one_or_none()
        if item.user_id != login_session['user_id']:
            flash('You are not authorized to edit this item. You must be the creator of an item to edit or delete it.')
            return redirect(url_for('showItem', medium_name=item.medium.name, item_id=item.id))
        else:
            return func(*args, **kwargs)
    return wrapper


def category_exists(func):
    """ Check if a category exists.

    This is a decorator that checks whether a category exists in
    the database. If the category does not exist, a 404 error
    is returned.
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        category = session.query(Medium).filter_by(name=kwargs['medium_name']).one_or_none()
        if not category:
            return abort(404)
        else:
            return func(*args, **kwargs)
    return wrapper


def item_exists(func):
    """ Check if a item exists.

    This is a decorator that checks whether an item exists in
    the database. If the category does not exist, a 404 error
    is returned.
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        item = session.query(ArtItem).filter_by(id=kwargs['item_id']).one_or_none()
        if not item:
            return abort(404)
        else:
            return func(*args, **kwargs)
    return wrapper


# JSON APIs to view item information
@views.route('/formific/medium/<medium_name>/JSON')
@category_exists
def showMediumItems(medium_name):
    """JSON endpoint to display all items in a specific category"""
    medium = session.query(Medium).filter_by(name=medium_name).one()
    items = session.query(ArtItem).filter_by(medium_id=medium.id).all()
    return jsonify(mediumItems=[i.serialize for i in items])


@views.route('/formific/items/JSON')
def showAllItems():
    """JSON endpoint to display all items in the database"""
    items = session.query(ArtItem).all()
    return jsonify(items=[i.serialize for i in items])


# Show all medium categories
@views.route('/', methods=['GET'])
@views.route('/formific', methods=['GET'])
def showForms():
    """Renders the main page populated with all items and categories"""
    formList = session.query(Medium).all()
    recentItems = (
            session.query(ArtItem).order_by(ArtItem.id.desc()).limit(12).all()
        )
    return render_template(
        'formific.html',
        media=formList,
        items=recentItems,
        userinfo=login_session
    )   


# Show all items in a category
@views.route('/formific/medium/<medium_name>/')
@views.route('/formific/medium/<medium_name>/item')
@category_exists
def showItems(medium_name):
    """Renders a page that displays all items within a specific category"""
    formList = session.query(Medium).all()
    medium = session.query(Medium).filter_by(name=medium_name).first()
    items = session.query(ArtItem).filter_by(medium_id=medium.id).all()
    return render_template(
        'items.html',
        medium=medium,
        items=items,
        media=formList,
        userinfo=login_session
    )


@views.route('/formific/medium/<medium_name>/item/<int:item_id>')
@category_exists
@item_exists
def showItem(medium_name, item_id):
    """Renders a page that displays a specific item in a category"""
    formList = session.query(Medium).all()
    item = session.query(ArtItem).filter_by(id=item_id).one()
    return render_template(
        'item.html',
        item=item,
        media=formList,
        userinfo=login_session
    )


@views.route('/formific/item/new', methods=['GET', 'POST'])
@login_required
def newItem():
    """Render a page that displays an HTML form to create a new item

    Renders a page with an HTML form. When the form is submitted a
    new item is created in the database with the form values submitted.
    """
    formList = session.query(Medium).all()
    if request.method == 'POST':
        newItem = ArtItem(
            name=request.form['name'],
            description=request.form['description'],
            material=request.form['material'],
            image_url=request.form['image_url'],
            video_url=request.form['video_url'],
            year=request.form['year'],
            medium_id=request.form['medium'],
            user_id=login_session['user_id']
        )
        session.add(newItem)
        session.commit()
        return redirect(url_for('showForms'))
    else:
        return render_template(
            'new-item.html',
            media=formList,
            userinfo=login_session
        )


@views.route('/formific/item/<int:item_id>/edit', methods=['GET', 'POST'])
@item_exists
@login_required
@item_modification_authentication
def editItem(item_id):
    """Render a page that displays an HTML form to edit an item

    Renders a page with an HTML form that allows the owner of the
    item to edit and update the item details.
    """
    formList = session.query(Medium).all()
    editedItem = session.query(ArtItem).filter_by(id=item_id).one()
    if request.method == 'POST':
        if request.form['name']:
            editedItem.name = request.form['name']
        if request.form['description']:
            editedItem.description = request.form['description']
        if request.form['material']:
            editedItem.material = request.form['material']
        if request.form['image_url']:
            editItem.image_url = request.form['image_url']
        if request.form['video_url']:
            editItem.video_url = request.form['video_url']
        if request.form['year']:
            editedItem.year = request.form['year']
        session.add(editedItem)
        session.commit()
        return redirect(url_for('showForms'))
    else:
        return render_template(
            'edit-item.html',
            item=editedItem,
            media=formList,
            userinfo=login_session
        )


@views.route('/formific/item/<int:item_id>/delete', methods=['GET', 'POST'])
@item_exists
@login_required
@item_modification_authentication
def deleteItem(item_id):
    """Render a page that displays an HTML input to delete an item

    Renders a page with an HTML input that allows the owner of the
    item to delete it.
    """
    formList = session.query(Medium).all()
    item = session.query(ArtItem).filter_by(id=item_id).one()
    if item.user_id != login_session['user_id']:
        flash('You are not authorized to edit this item. You must be the creator of an item to edit or delete it.')
        return redirect(url_for('showItem', medium_name=item.medium.name, item_id=item.id))    
    if request.method == 'POST':
        session.delete(item)
        session.commit()
        return redirect(url_for('showForms'))
    else:
        return render_template(
            'delete-item.html',
            item=item,
            media=formList,
            userinfo=login_session
        )

formificApp/formificApp/templates/401.html
{% extends "wrapper.html" %}
{% block content %}

			<div class="content__head grid">
				<h2 class="content__title grid__cell">401</h2>
			</div>

			<h3>Sorry, your login failed, please try again :-(</h3>

{% endblock %}

formificApp/formificApp/templates/access.html
<div class="content__access">

	{% if 'username' not in session %}
	
		<a class="btn btn--primary" href="{{ url_for('auth.showLogin') }}">Login</a>

	{% else %}

		<a class="btn btn--primary" href="{{ url_for('views.newItem') }}">Add New Item</a>

		<a class="btn btn--primary" href="{{ url_for('auth.disconnect') }}">Logout</a>
		
		<div class="userinfo">
			<img class="userinfo__img" src="{{userinfo['picture']}}" alt="{{userinfo['username']}}" width="44">
			<span class="userinfo__name">{{userinfo['username']}}</span>
		</div>

	{% endif %}	

</div>

formificApp/formificApp/templates/delete-item.html
{% extends "wrapper.html" %}
{% block content %}

			<div class="content__head grid">
				<h2 class="content__title grid__cell">Delete Item</h2>

				{% include "access.html" %}

			</div>
			<h3>Are you sure you want to delete item: "{{item.name}}"?</h3>
			<form class="form" action="{{ url_for('views.deleteItem', item_id=item.id) }}" method="post">
				<input class="btn btn--secondary-reverse" type="submit" name="submit" value="Delete">
				<a class="btn btn--secondary-reverse" href="{{ url_for('views.showForms') }}">Cancel</a>
			</form>

{% endblock %}

formificApp/formificApp/templates/edit-item.html
{% extends "wrapper.html" %}
{% block content %}

			<div class="content__head grid">
				<h2 class="content__title grid__cell">Edit item: "{{item.name}}"</h2>

				{% include "access.html" %}

			</div>

				<form class="form" action="{{ url_for('views.editItem', item_id=item.id) }}" method="post">
					<div class="form__row">
						<label class="label" for="name">Name:</label>
						<input class="input" type="text" name="name" placeholder="{{item.name}}">
					</div>
					<div class="form__row">
						<label class="label" for="description">Description:</label>
						<textarea class="textarea" type="text" name="description">{{item.description}}</textarea>
					</div>
					<div class="form__row">
						<label class="label" for="material">Material:</label>
						<input class="input" type="text" name="material" placeholder="{{item.material}}">
					</div>
					<div class="form__row">
						<label class="label" for="year">Year:</label>
						<input class="input" type="text" name="year" placeholder="{{item.year}}">
					</div>
					<div class="form__row">
						<label class="label" for="image_url">URL:</label>
						<input class="input" type="text" name="image_url" placeholder="{{item.image_url}}">
					</div>
						
					{% if item.medium.name == 'Video' or item.medium.name == 'video' %}
					
					<div class="form__row">
						<label class="label" for="video_url">Video URL:</label>
						<input class="input" type="text" name="video_url" placeholder="{{item.video_url}}">
					</div>
						
					{% endif %}

					<input class="btn btn--secondary-reverse" type="submit" name="submit" value="Update">
					<a class="btn btn--secondary-reverse" href="{{ url_for('views.showForms') }}">Cancel</a>
				</form>

{% endblock %}

formificApp/formificApp/templates/formific.html
{% extends "wrapper.html" %}
{% block content %}

			<div class="content__head grid">
				<h2 class="content__title grid__cell">Recent Items:</h2>

				{% include "access.html" %}

			</div>
			
			<div class="masonry">
				
				{% for item in items %}

				<div class="masonry__brick">
					<a href="{{ url_for('views.showItem', medium_name=item.medium.name, item_id=item.id) }}">
						<img class="masonry__img" src="{{item.image_url}}" alt="{{item.name}}">
					</a>
				</div>

				{% endfor %}

			</div>
	
{% endblock %}	

formificApp/formificApp/templates/header.html
<div class="identity">
	<h1 class="identity__logo"><a href="{{ url_for('views.showForms') }}">Formific</a></h1>
	<p class="identity__tagline">a collection of (hand)made things</p>	
</div>
<div id="nav__icon" class="nav__icon">
	<span></span>
	<span></span>
	<span></span>
	<span></span>
</div>
<nav class="nav">

	{% for medium in media %}

	<a class="nav__item text-caps" href="{{ url_for('views.showItems', medium_name=medium.name) }}">{{medium.name}}</a>

	{% endfor %}

</nav>

formificApp/formificApp/templates/item.html
{% extends "wrapper.html" %}
{% block content %}

			<div class="content__head grid">
				<h2 class="content__title grid__cell">{{item.medium.name}}</h2>

				{% include "access.html" %}

			</div>
			
			<div class="content__body">

				<div class="grid">
					<div class="grid__cell">
						<img src="{{item.image_url}}" width="450">
					</div>
					<div class="grid__cell">
						<div class="item__container">
							<h3>{{item.name}}</h3>
							<p>{{item.description}}</p>

							{% if item.medium.name == 'Video' %}
							
							<a class="btn btn--primary" href="{{item.video_url}}" target="_blank">Watch video</a>

							{% endif %}

							{% if item.user_id == userinfo['user_id'] %}
							
							<a class="btn btn--secondary-reverse" href="{{ url_for('views.editItem', medium_name=item.medium.name, item_id=item.id) }}">Edit</a>
							<a class="btn btn--secondary-reverse" href="{{ url_for('views.deleteItem', medium_name=item.medium.name, item_id=item.id) }}">Delete</a>
							
							{% endif %}

							
						</div>	
					</div>
				</div>

			</div>

{% endblock %}

formificApp/formificApp/templates/items.html
{% extends "wrapper.html" %}
{% block content %}

			<div class="content__head grid">
				<h2 class="content__title grid__cell">{{medium.name}} Items</h2>

				{% include "access.html" %}

			</div>

			<div class="masonry">

				{% for item in items %}

				<div class="masonry__brick">
					<a href="{{ url_for('views.showItem', medium_name=item.medium.name, item_id=item.id) }}">
						<img class="masonry__img" src="{{item.image_url}}" alt="{{item.name}}">
					</a>
				</div>

				{% endfor %}
				
			</div>

{% endblock %}

formificApp/formificApp/templates/new-item.html
{% extends "wrapper.html" %}
{% block content %}

			<div class="content__head grid">
				<h2 class="content__title grid__cell">Add a new item to Formific!</h2>

				{% include "access.html" %}

			</div>

			<form class="form" action="{{ url_for('views.newItem') }}" method="post">
				<div class="form__row">
					<label class="label" for="name">Name:</label>
					<input class="input" type="text" name="name">
				</div>
				<div class="form__row">
					<label class="label" for="description">Description:</label>
					<textarea class="textarea" type="text" name="description"></textarea>
				</div>
				<div class="form__row">
					<label class="label" for="material">Material:</label>
					<input class="input" type="text" name="material">
				</div>
				<div class="form__row">
					<label class="label" for="year">Year:</label>
					<input class="input" type="text" name="year">
				</div>
				<div class="form__row">
					<label class="label" for="image_url">Image URL:</label>
					<input class="input" type="text" name="image_url">
				</div>
				<div class="form__row">
					<label class="label" for="video_url">Video URL:</label>
					<input class="input" type="text" name="video_url">
				</div>
				<div class="form__row">
					<label class="label" for="medium">Medium:</label>
					<select class="select" name="medium">

						{% for medium in media %}

						<option value="{{medium.id}}">{{medium.name}}</option>

						{% endfor %}

					</select>
				</div>
				<input class="btn btn--secondary-reverse" type="submit" name="submit" value="Create">
			</form>

{% endblock %}

formificApp/formificApp/templates/wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Formific: A collection of (hand)made things</title>
	<link href="https://fonts.googleapis.com/css?family=Quicksand|Roboto:400,700" rel="stylesheet">
	<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
	<div class="page">

		<div class="container">
		
			<div class="sidebar">

				{% include "header.html" %}

			</div>

			<div class="header__mobile">
				
				{% include "header.html" %}

			</div>

			<div class="content">

				<div class="alert-box">

				{% with messages = get_flashed_messages() %}

					{% if messages %}

					{% for message in messages %}

					<div class="alert-box__msg show">{{ message }} <span class="alert-box__close">×</span></div>

					{% endfor %}

					{% endif %}

				{% endwith %}

				</div>	

			{% block content %}

			{% endblock %}
			
			</div>	

		</div>

	</div>

	<script type="text/javascript" src="{{ url_for('static', filename='formific.js') }}"></script>
</body>
</html>